### PR TITLE
Allow user to define his own backend.

### PR DESCRIPTION
**Pull request by Djabx**
Move from: https://github.com/GoogleCloudPlatform/professional-services/pull/517

### CODE REVIEW

**Comment by ocervell** [comment]
Thanks ! Would you mind adding an example custom backend ? 

You can create a folder in `samples/` called `custom` and add a SLO YAML sample (anonymized) + Python custom backend example for it.

**Comment by ocervell** [comment]
Another small issue: it doesn't work with the CLI, the current path needs to be appended to the pythonpath in `slo_generator/cli.py`:
```
import os
import sys
sys.path.append(os.getcwd())  ## dynamic backend loading
```

**Comment by Djabx** [comment]
> Another small issue: it doesn't work with the CLI, the current path needs to be appended to the pythonpath in `slo_generator/cli.py`:

How to you test this ?
I've:
* create a virtual env
* install the cli in it
* do the command: `cd samples && slo-generator -f stackdriver/slo_gae_app_availability.yaml -b error_budget_policy.yaml`

And no problem for loading the class defined.

**Comment by Djabx** [comment]
@ocervell should good I suppose ?

**Comment by ocervell** [comment]
Sure - I will merge this and add an example in a further PR for:
* **custom backend:** add sample
* **custom exporter:** not reuse the same code as Stackdriver exporter
* **cli:** add the folder we load SLOs from to PYTHONPATH as well, as custom code will probably be located there

**Review by ocervell — APPROVED** [review]

**Pull request merged**
