### PR TITLE
alerting_burn_rate_threshold should be float

### PR DESCRIPTION
**Pull request by anas-aso**
Currently only the int part is taken leading to false alerts.

### CODE REVIEW

**Comment by anas-aso** [comment]
@ocervell as [requested](https://github.com/GoogleCloudPlatform/professional-services/pull/568#issuecomment-704410414) I have reopened my PR in this repo.

**Comment by ocervell** [comment]
Tests are failing, could you please merge the latest master into your branch ?
```
git checkout patch-1
git merge master
```

**Comment by ocervell** [comment]
please merge master into your branch to make the tests pass :)

**Comment by anas-aso** [comment]
@ocervell done. Tests are green.

**Pull request merged**
