### PR TITLE
fix(open_search): change the way range is added to filters

### PR DESCRIPTION
**Pull request by maximepln**
-- Actual Behaviour -- 

When using the open_search backend you cannot use filters in the query.

```
backend: open_search
error_budget_policy: 28days
method: good_bad_ratio
service_level_indicator:
    index: "gravitee-request-*"
    date_field: '@timestamp'
    query_good:
        filter:
            - match:
                api: some-data
            - range:
                status:
                    gte: 200
                    lt: 299
    query_bad:
        filter:
            - match:
                api: some-data
        must_not:
            range:
                status:
                    lt: 299
goal: 0.99

```
    
The backend will throw the following error `TypeError: list indices must be integers or slices, not str`
    
-- Fix -- 

To avoid this error we must use append instead of directly assigning range = range_query (Furthermore, even if the actual code was working it would erase any range filter made in the yaml without informing the user which could have bring confusion).

### CODE REVIEW

**Comment by maximepln** [comment]
Hi @lvaylet,

A little PR to help us use `filter` keyword which is more optimised than `must` keyword.

Do not hesitate to propose any suggestion if you have some.

**Comment by maximepln** [comment]
Looking back at the issue, I'm going to change my approach, the idea of having filters as a dict is wrong, as it doesn't authorize the use of multiple term in the same filter per example. I'll try to come up with something that will cover most of the use cases

**Comment by maximepln** [comment]
Hello again @lvaylet, 

I came up with a better solution, the idea is to transform everything under filter from a dict to an array (doesn't change the behaviour I tested it on my side). The advantage of doing that is that now we are able to use multiple `range` keyword and only the one equal to the `date_field` is replaced. 

You can check that on the test I added, but if you want a quick look: 
```
spec:
  description: 99% of the element are valid
  backend: open_search
  method: good_bad_ratio
  exporters: []
  service_level_indicator:
    index: "gravitee-request-*"
    date_field: '@timestamp'
    query_good:
      filter:
        - range:
            status:
              lt: 299
        - term:
            api: "f7ad3478-b9a7-4714-ad34-78b9a7b7143e"
    query_bad:
      filter:
        - term:
            api: "f7ad3478-b9a7-4714-ad34-78b9a7b7143e"
        - range:
            status:
              gt: 299
    goal: 0.99
```

In this case for example, this 
```
        - range:
            status:
              gt: 299
```
would have been 'magically' removed, that's not the case anymore.

**Comment by maximepln** [comment]
Hello @lvaylet,

Any news on this PR ?

Thanks in advance,

**Comment by lvaylet** [comment]
I will take a look tomorrow. I must admit I have been pretty busy since the beginning of the year.

**Comment by lvaylet** [comment]
Looks good to me. Moving forward with merge.

**Pull request merged**
